set(_CATKIN_CURRENT_PACKAGE "Monster_Truck_UI")
set(Monster_Truck_UI_VERSION "0.1.0")
set(Monster_Truck_UI_MAINTAINER "alex <alex@gmail.com>")
set(Monster_Truck_UI_PACKAGE_FORMAT "1")
set(Monster_Truck_UI_BUILD_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(Monster_Truck_UI_BUILD_EXPORT_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(Monster_Truck_UI_BUILDTOOL_DEPENDS "catkin")
set(Monster_Truck_UI_BUILDTOOL_EXPORT_DEPENDS )
set(Monster_Truck_UI_EXEC_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(Monster_Truck_UI_RUN_DEPENDS "qt_build" "roscpp" "libqt4-dev")
set(Monster_Truck_UI_TEST_DEPENDS )
set(Monster_Truck_UI_DOC_DEPENDS )
set(Monster_Truck_UI_URL_WEBSITE "")
set(Monster_Truck_UI_URL_BUGTRACKER "")
set(Monster_Truck_UI_URL_REPOSITORY "")
set(Monster_Truck_UI_DEPRECATED "")